export enum CrewAction {
  SEND_SMS = 'SEND_SMS',
  ASSIGN = 'ASSIGN',
  NOTIFY = 'NOTIFY',
  REJECT = 'REJECT',
  MARK_AS_CREW_CHIEF = 'MARK_AS_CREW_CHIEF',
  MARK_AS_TEAM_LEADER = 'MARK_AS_TEAM_LEADER',
  CONFIRM = 'CONFIRM',
  TURN_DOWN = 'TURN_DOWN',
  REMOVE = 'REMOVE',
  MARK_AS_NO_SHOW = 'MARK_AS_NO_SHOW',
  CHANGE = 'CHANGE'
}
